packages:
  # All applications in subdirs of apps/
  - "apps/**"
  # All libraries in subdirs of library/
  - "libs/**"
  # All ui elements and components in subdirs of ui/
  - "ui/**"
  # All app routing and page views in subdirs of views/
  - "view/**"
  # All assets in subdirs of (outside) assets folder
  - "../assets/**"