packages:
  # All additional tools for tests and development
  - "_tooling/**"
  # All applications in subdirs of apps/
  - "apps/**"
  # All ui elements and components in subdirs of ui/
  - "ui/**"
  # All app routing and page views in subdirs of views/
  - "views/**"
  # All assets in subdirs of (outside) assets folder
  - "../assets/**"
  # All feature tests and specifications in subdirs of (outside) features folder
  - "../features/**"